name: Daily Bonus

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 02 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BILIBILI_BILI_JCT: ${{ secrets.BILIBILI_BILI_JCT }}
      BILIBILI_DEDEUSERID: ${{ secrets.BILIBILI_DEDEUSERID }}
      BILIBILI_SESSDATA: ${{ secrets.BILIBILI_SESSDATA }}
      MUSIC_CELLPHONE: ${{ secrets.MUSIC_CELLPHONE }}
      MUSIC_PASSWORD: ${{ secrets.MUSIC_PASSWORD }}
      YAMIBO_YJS_JS_SECURITY_PASSPORT: ${{ secrets.YAMIBO_YJS_JS_SECURITY_PASSPORT }}
      YAMIBO_EEQY_2132_SALTKEY: ${{ secrets.YAMIBO_EEQY_2132_SALTKEY }}
      YAMIBO_EEQY_2132_AUTH: ${{ secrets.YAMIBO_EEQY_2132_AUTH }}
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      PICA_EMAIL: ${{ secrets.PICA_EMAIL }}
      PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_TOKEN: ${{ secrets.BARK_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Echo current time
        run: timedatectl
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check-in
        run: python ./message.py
        if: always()
